# Setup
title:               SunFarm
tagline:             'Enhancing ASNA Monarch Nomad Migration Guide'
description:         'IBMi Modernization Developer Guide'
url:                 https://asna.github.io/SunFarm/
baseurl:             '/'
paginate:            5
permalink:           pretty
markdown: kramdown

# About/contact
author:
  name:              Jorge V. Contreras
  url:               https://twitter.com/JVContrera
  email:             jcontreras@asna.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             2.0.0
google_analytics_id: #UA-XXXX-Y
